<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Advertising Data Analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Advertising Data Analysis</h1>

</div>


<p>Read the advertising.csv data and store it in AdData.</p>
<pre class="r"><code>AdData &lt;- read.csv(&quot;/Users/Shima/R_projects/advertising_data/advertising.csv&quot;, header = TRUE)
head(AdData)</code></pre>
<pre><code>##      TV radio newspaper sales
## 1 230.1  37.8      69.2  22.1
## 2  44.5  39.3      45.1  10.4
## 3  17.2  45.9      69.3   9.3
## 4 151.5  41.3      58.5  18.5
## 5 180.8  10.8      58.4  12.9
## 6   8.7  48.9      75.0   7.2</code></pre>
<p>Prints the column names of the dataset AdData:</p>
<pre class="r"><code>names(AdData)</code></pre>
<pre><code>## [1] &quot;TV&quot;        &quot;radio&quot;     &quot;newspaper&quot; &quot;sales&quot;</code></pre>
<p>Rearrange the columns so that sales becomes the first column in the data set:</p>
<pre class="r"><code>col_order &lt;- c(&quot;sales&quot;, &quot;TV&quot;, &quot;radio&quot;, &quot;newspaper&quot;)
AdData &lt;- AdData[,col_order]
head(AdData)</code></pre>
<pre><code>##   sales    TV radio newspaper
## 1  22.1 230.1  37.8      69.2
## 2  10.4  44.5  39.3      45.1
## 3   9.3  17.2  45.9      69.3
## 4  18.5 151.5  41.3      58.5
## 5  12.9 180.8  10.8      58.4
## 6   7.2   8.7  48.9      75.0</code></pre>
<p>Automatically tests regression models that have only one single predictor variable using the following variable changes: sqrt(), variable to the square, or multiplication of two variables.</p>
<pre class="r"><code># new dataframe with the new predictor variables 
# sales is the prediction (y variable)
# followed by square root / squared / multiplication of other variables 
AdData2 &lt;- data.frame (&quot;Sales&quot; = AdData$sales, &quot;TV&quot;=AdData$TV, &quot;sqrtTV&quot; = sqrt(AdData$TV), &quot;TV^2&quot;= (AdData$TV)^2, &quot;TV*Radio&quot; = (AdData$TV*AdData$radio),&quot;TV*Paper&quot; = (AdData$TV*AdData$newspaper), &quot;Radio&quot; = AdData$radio, &quot;sqrtRadio&quot; = sqrt(AdData$radio), &quot;Radio^2&quot; = (AdData$radio)^2, &quot;Radio*Newspaper&quot; = (AdData$radio * AdData$newspaper),  &quot;Newspaper&quot; = AdData$newspaper, &quot;sqrtNewspaper&quot; = sqrt(AdData$newspaper), &quot;Newspaper^2&quot; = (AdData$newspaper)^2)
head(AdData2)</code></pre>
<pre><code>##   Sales    TV    sqrtTV     TV.2 TV.Radio TV.Paper Radio sqrtRadio Radio.2
## 1  22.1 230.1 15.169047 52946.01  8697.78 15922.92  37.8  6.148170 1428.84
## 2  10.4  44.5  6.670832  1980.25  1748.85  2006.95  39.3  6.268971 1544.49
## 3   9.3  17.2  4.147288   295.84   789.48  1191.96  45.9  6.774954 2106.81
## 4  18.5 151.5 12.308534 22952.25  6256.95  8862.75  41.3  6.426508 1705.69
## 5  12.9 180.8 13.446189 32688.64  1952.64 10558.72  10.8  3.286335  116.64
## 6   7.2   8.7  2.949576    75.69   425.43   652.50  48.9  6.992853 2391.21
##   Radio.Newspaper Newspaper sqrtNewspaper Newspaper.2
## 1         2615.76      69.2      8.318654     4788.64
## 2         1772.43      45.1      6.715653     2034.01
## 3         3180.87      69.3      8.324662     4802.49
## 4         2416.05      58.5      7.648529     3422.25
## 5          630.72      58.4      7.641989     3410.56
## 6         3667.50      75.0      8.660254     5625.00</code></pre>
<pre class="r"><code># testing and training sets 
num_samples=dim(AdData2) [1]
sampling.rate = 0.8
training &lt;- sample(1:num_samples,sampling.rate*num_samples,replace = FALSE)
trainingSet &lt;- subset(AdData2[training,])
testing &lt;- setdiff(1:num_samples,training)
testingSet &lt;- subset(AdData2[testing,])

# automatic testing of regModels in for loop - picks the model with lowest mse
# min is initialized to a really big number for the first loop
min &lt;- 1000000000000000
# loop through the new cols (new variables) - exclude sales so loop starts at 2 
for(i in 2:(length(AdData2))) {
  # current model (i)
  regModel &lt;- lm(Sales~get(names(AdData2[i])),data = trainingSet)  
  # error = sales predictions from current model (i) -  actual sales predictions from testing set
  error &lt;- predict(regModel,testingSet,type=&quot;response&quot;) - testingSet$Sales
  mse &lt;- mean(error^2)
  # check if we encountred a new min mse
  if(mse&lt;min) {
    min &lt;- mse
    finalRegModel &lt;- regModel
    index &lt;- i 
  }
}</code></pre>
<p>Identify the model with the best performance</p>
<pre class="r"><code>paste(&quot;The model with best performance is based on the&quot;, names(AdData2[index]), &quot;column with a mean squared error of:&quot;, min)</code></pre>
<pre><code>## [1] &quot;The model with best performance is based on the TV.Radio column with a mean squared error of: 1.81949686106092&quot;</code></pre>
<pre class="r"><code>summary(finalRegModel)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Sales ~ get(names(AdData2[i])), data = trainingSet)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.2795 -0.4495  0.1969  0.8404  2.7185 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            8.838e+00  1.620e-01   54.56   &lt;2e-16 ***
## get(names(AdData2[i])) 1.486e-03  3.266e-05   45.51   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.403 on 158 degrees of freedom
## Multiple R-squared:  0.9291, Adjusted R-squared:  0.9287 
## F-statistic:  2071 on 1 and 158 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>For the model with the best performance, calculate the residuals and display them using a histogram.</p>
<pre class="r"><code>plot(hist(residuals(finalRegModel)))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-6-2.png" width="672" /> Use the residuals to also plot the normal probability plot that also shows the corresponding straight line. We can see that most of the errors are normlly distirbuted. Except the first bit where we see some of the errors are lower than the rest. This could be because we did not clean the data before running the model.</p>
<pre class="r"><code>qqnorm(residuals(finalRegModel))
qqline(residuals(finalRegModel))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" width="672" /> Read the advertising_set2.csv data</p>
<pre class="r"><code>AdSet &lt;- read.csv(&quot;advertising_set2.csv&quot;, header = TRUE)
head(AdSet)</code></pre>
<pre><code>##       TV  radio newspaper  sales id
## 1 649.63 111.45    227.21  64.08  2
## 2 978.97 220.80    204.15 118.53  2
## 3 701.34 102.29    147.78  70.22  3
## 4 166.75  31.74     52.60  24.41  3
## 5 103.63  98.46    183.98  28.16  3
## 6 561.58 127.84    108.75  60.44  3</code></pre>
<p>Create a decision tree model to predict Sales</p>
<pre class="r"><code># load library
library(rpart)

# create decision tree model based on sales 
decTreeModel &lt;- rpart(sales~.-id, data=AdSet)
plot(decTreeModel, margin=0.1)
text(decTreeModel)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code># prune tree at 0.016
plotcp(decTreeModel) </code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<pre class="r"><code>pruned_decTreeModel = prune(decTreeModel,cp=0.016)
plot(pruned_decTreeModel,margin = 0.01)
text(pruned_decTreeModel)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-9-3.png" width="672" /></p>
<pre class="r"><code>plotcp(decTreeModel) </code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-9-4.png" width="672" /> Create a linear regression model (do not create non-linear models)</p>
<pre class="r"><code>linRegModel &lt;- lm(sales~.-id,data=AdSet)
summary(linRegModel)</code></pre>
<pre><code>## 
## Call:
## lm(formula = sales ~ . - id, data = AdSet)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -41.721  -3.156  -2.200   3.612  28.795 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.8640961  0.4877766   5.872 7.17e-09 ***
## TV          0.0515923  0.0008661  59.566  &lt; 2e-16 ***
## radio       0.2177832  0.0060108  36.232  &lt; 2e-16 ***
## newspaper   0.0149192  0.0041557   3.590 0.000358 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.181 on 596 degrees of freedom
## Multiple R-squared:  0.9536, Adjusted R-squared:  0.9533 
## F-statistic:  4079 on 3 and 596 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The equation of the regression function f(x) is as follows:<br />
b0 is the intecept, and the coefficients b1,b2,b3 can be multipled by the amount of TV, radio, and newspaper x1,x2,x3 respectively.<br />
Equation = b0 + b1(x1) + b2(x2) + b3(x3)<br />
Equation = 2.8640961 + 0.0515923(x1) + 0.2177832(x2) + 0.0149192(x3)<br />
(where x1, x2, x3 represent the amounts of TV, radio and newspaper respectively)</p>
<pre class="r"><code># intecept
b0 &lt;- 2.8640961

# TV
b1 &lt;- 0.0515923

# radio
b2 &lt;- 0.2177832

# newspaper
b3 &lt;- 0.0149192</code></pre>
<p>Evaluate both models and recommend a model that can be used for predictions.</p>
<pre class="r"><code># create testing / training datasets
num_samples = dim(AdSet)[1]
sampling.rate = 0.8
training&lt;-sample(1:num_samples,sampling.rate*num_samples,replace = TRUE)
trainingset &lt;- subset(AdSet[training,])
testing &lt;- setdiff(1:num_samples,training)
testingset &lt;- subset(AdSet[testing,])

# create regression model 
regModel &lt;- lm(sales~.-id, data=trainingset)

# predict sales using regression model
regModelPrediction &lt;- predict(regModel,testingset)

# evaluate regression model
regModelError = regModelPrediction-testingset$sales
regModelMSE = mean(regModelError^2)

# creating decision tree model again (same as above)
decTreeModel &lt;- rpart(sales~.-id, data=AdSet)
plot(decTreeModel, margin=0.1)
text(decTreeModel)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code># prune tree at 0.016
plotcp(decTreeModel) </code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<pre class="r"><code>pruned_decTreeModel = prune(decTreeModel,cp=0.016)
plot(pruned_decTreeModel,margin = 0.01)
text(pruned_decTreeModel)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-12-3.png" width="672" /></p>
<pre class="r"><code>plotcp(decTreeModel) </code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-12-4.png" width="672" /></p>
<pre class="r"><code># predict sales using dec tree model 
decTreeModelPrediction &lt;- predict(pruned_decTreeModel,testingset)
decTreeModelError = decTreeModelPrediction - testingset$sales
decTreeModelMSE = mean(decTreeModelError^2)

if (regModelMSE&gt;decTreeModelMSE){
  paste(&quot;Decision Tree Model is reccomended due to a lower mean squared error of&quot;, regModelMSE)
} else {
  paste(&quot;Regression Model is reccomended due to a lower mean squared error of&quot;, decTreeModelMSE )
}</code></pre>
<pre><code>## [1] &quot;Regression Model is reccomended due to a lower mean squared error of 128.347456681621&quot;</code></pre>
<p><strong>Regression Models</strong></p>
<p><em>Advantages</em><br />
- Even when a linear regression model does not fit the data exactly, we can use it to find the nature of the relationship between the two variables.</p>
<p><em>Disadvantages</em><br />
- A linear regression model works under the assumption that there is a straight-line relationship between vaiables in the linear regression model. This could be incorrect at times, leading to the model becoming significantly influenced by outliners and anomalies in the data.</p>
<p><strong>Decision Tree Models</strong></p>
<p><em>Advantages</em><br />
- Decision tree models do not require data normalization / scaling.<br />
- Missing values in data of decision tree models do not affect the outcome of the model.</p>
<p><em>Disadvantages</em><br />
- Because data gets fragmented by each split in a decision tree model, the model created at each split will potentially introduce bias into the overall result.<br />
- Decision tree models have a higher probability of overfitting.</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
